# action.yml
name: 'VUnit Action (Moved)'
description: 'Automatically test your vhdl code with VUnit. Moved here: https://github.com/VUnit/vunit_action/'
inputs:
  run_file:
    description: 'python vunit run file'
    default: 'run.py'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.run_file }}
branding:
  icon: cpu
  color: blue
